package com.vcjain.cxfsoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2013-12-27T11:25:37.737+05:30
 * Generated source version: 3.0.0-milestone1
 * 
 */
@WebServiceClient(name = "EmpService", 
                  wsdlLocation = "file:/D:/IDE/eclispe/workspace/tutorial/webservice/cxfclient/src/main/resources/wsdl/employee.wsdl",
                  targetNamespace = "http://cxfsoap.vcjain.com/") 
public class EmpService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxfsoap.vcjain.com/", "EmpService");
    public final static QName EmpServicePort = new QName("http://cxfsoap.vcjain.com/", "EmpServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/IDE/eclispe/workspace/tutorial/webservice/cxfclient/src/main/resources/wsdl/employee.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmpService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/IDE/eclispe/workspace/tutorial/webservice/cxfclient/src/main/resources/wsdl/employee.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmpService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmpService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmpService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmpService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmpService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns EmpService
     */
    @WebEndpoint(name = "EmpServicePort")
    public EmpService getEmpServicePort() {
        return super.getPort(EmpServicePort, EmpService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpService
     */
    @WebEndpoint(name = "EmpServicePort")
    public EmpService getEmpServicePort(WebServiceFeature... features) {
        return super.getPort(EmpServicePort, EmpService.class, features);
    }

}
