
package com.vcjain.cxfsoap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2013-12-27T11:25:37.713+05:30
 * Generated source version: 3.0.0-milestone1
 */

@WebFault(name = "NameMismatchFaultDetails", targetNamespace = "http://cxfsoap.vcjain.com/")
public class NameMisMatchException extends Exception {
    
    private com.vcjain.cxfsoap.NameMismatchFaultDetails nameMismatchFaultDetails;

    public NameMisMatchException() {
        super();
    }
    
    public NameMisMatchException(String message) {
        super(message);
    }
    
    public NameMisMatchException(String message, Throwable cause) {
        super(message, cause);
    }

    public NameMisMatchException(String message, com.vcjain.cxfsoap.NameMismatchFaultDetails nameMismatchFaultDetails) {
        super(message);
        this.nameMismatchFaultDetails = nameMismatchFaultDetails;
    }

    public NameMisMatchException(String message, com.vcjain.cxfsoap.NameMismatchFaultDetails nameMismatchFaultDetails, Throwable cause) {
        super(message, cause);
        this.nameMismatchFaultDetails = nameMismatchFaultDetails;
    }

    public com.vcjain.cxfsoap.NameMismatchFaultDetails getFaultInfo() {
        return this.nameMismatchFaultDetails;
    }
}
